version: '2'
services:
  vpn:
    container_name: vpn
    image: dceschmidt/openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    restart: unless-stopped
    ports:
      - "1022:22"
      - "8888:8888"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      OPENVPN_PROVIDER: ${OPENVPN_PROVIDER}
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_CONFIG: ${OPENVPN_CONFIG}
      OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
      LOCAL_NETWORK: 100.115.92.200/28
  tinyproxy:
    container_name: tinyproxy
    image: vimagick/tinyproxy
    depends_on:
      - vpn
    network_mode: "service:vpn"
    restart: unless-stopped
  popcorn:
    container_name: popcorn
    depends_on:
      - vpn
    network_mode: "service:vpn"
    build:
      context: ./popcorn
      args:
        USERNAME: ${USERNAME}
    mem_limit: 2G
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTH}
      PULSE_SERVER: unix:/run/user/1000/pulse/native
    volumes:
      - ${XAUTH}:${XAUTH}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /var/run/dbus:/var/run/dbus
      - ${POPCORN_DATA_DIR}:/home/${USERNAME}/.config/Popcorn-Time
