version: '2'
services:
  vpn:
    container_name: vpn
    #image: dceschmidt/openvpn-client
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
    - /dev/net/tun
    restart: unless-stopped
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
      - ${TRANSMISSION_PORT}:9091
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TRANSMISSION_TORRENTS_DIR}:/data
    environment:
      CREATE_TUN_DEVICE: 'true'
      OPENVPN_PROVIDER: ${OPENVPN_PROVIDER}
      OPENVPN_USERNAME: ${OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_CONFIG: ${OPENVPN_CONFIG}
      OPENVPN_OPTS: "--inactive 3600 --ping 10 --ping-exit 60"
      WEBPROXY_ENABLED: 'true'
      WEBPROXY_PORT: ${PROXY_PORT}
      LOCAL_NETWORK: 100.115.92.200/28
  popcorn:
    container_name: popcorn
    depends_on:
      - vpn
    network_mode: "service:vpn"
    build:
      context: ./popcorn
      args:
        USERNAME: ${USERNAME}
    mem_limit: 2G
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTH}
      PULSE_SERVER: unix:/run/user/1000/pulse/native
    volumes:
      - ${POPCORN_CFG_DIR}:/home/${USERNAME}/.config/Popcorn-Time
      - ${POPCORN_TORRENTS_DIR}:/tmp/Popcorn-Time
      - ${XAUTH}:${XAUTH}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /var/run/dbus:/var/run/dbus
      - /dev/dri:/dev/dri
networks:
  default:
    driver: bridge
    ipam:
     driver: default
    driver_opts:
      com.docker.network.bridge.name: ${VPN_BRIDGE_NAME}
